version: "3.7"

services:

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: journal


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: journal_app
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/journal